In [0]:
wordlen = max(df['word_count'])
print(wordlen)

24177


In [0]:
%tensorflow_version 1.14

#importing libraries

from numpy import array
from numpy import asarray
from numpy import zeros
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten, BatchNormalization
from keras.layers import Embedding, Dropout, Conv1D, MaxPooling1D
import pandas as pd
from sklearn.model_selection import train_test_split


#Loading the data in a dataframe



df = pd.read_csv('drive/My Drive/The_Research/all_data_refined.csv')
docs = df['text'] #Change this accordingly


#test

for i in range(len(docs)):
  if docs[i] == "": print(i)

#load the labels


type = df['type'] #Change this accordingly
labels = []

for types in type:
  if types == 'real':
    labels.append(1)
  elif types == 'fake':
    labels.append(0)


print(docs)

# prepare tokenizer
t = Tokenizer()
t.fit_on_texts(docs)
vocab_size = len(t.word_index) + 1



# integer encode the documents
encoded_docs = t.texts_to_sequences(docs)
print(encoded_docs)


# pad documents to a max length




wordlen = max(df['word_count'])
print(wordlen)





max_length = wordlen # Change this if needed
print("Max_Length: ", max_length)
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)


# load the whole embedding into memory
embeddings_index = dict()
f = open('drive/My Drive/glove_data/glove.6B/glove.6B.100d.txt')
for line in f:
	values = line.split()
	word = values[0]
	coefs = asarray(values[1:], dtype='float32')
	embeddings_index[word] = coefs
f.close()
print('Loaded %s word vectors.' % len(embeddings_index))


# create a weight matrix for words in training docs
embedding_matrix = zeros((vocab_size, 100))
for word, i in t.word_index.items():
	embedding_vector = embeddings_index.get(word)
	if embedding_vector is not None:
		embedding_matrix[i] = embedding_vector


X_train, X_test, y_train, y_test = train_test_split(padded_docs, labels, test_size=0.33)

# define model
model = Sequential()
e = Embedding(vocab_size, 100, weights=[embedding_matrix], input_length=max_length, trainable=False)
model.add(e)
model.add(Dropout(0.5))
#model.add(e)
model.add(Conv1D(filters=10, kernel_size=(4)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.8))
model.add(Dense(1, activation='sigmoid'))


# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


# summarize the model
print("____________________")
print(model.summary())
print("____________________")


# fit the model
model.fit(X_train, y_train, epochs=5, verbose=1)


# evaluate the model
print("____________________")
loss, accuracy = model.evaluate(X_test, y_test, verbose=1)
print('Accuracy: %f' % (accuracy*100))


print("____________________")
output = model.predict(X_test)
print(output)

# save the model
model.save('modelword2vec.h5')


`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `1.14`. This will be interpreted as: `1.x`.


TensorFlow is already loaded. Please restart the runtime to change versions.
0        They stood in line at Trump Tower, sometimes u...
1        Donald J. Trump s foundation informed Attorney...
2        President-elect Donald J. Trump won the White ...
3        An investment pitch for a new Texas hotel is t...
4        President-elect Donald J. Trump s wife, Melani...
                               ...                        
20010    Most conservatives who oppose marriage equalit...
20011    The freshman senator from Georgia quoted scrip...
20012    The State Department told the Republican Natio...
20013    ADDIS ABABA, Ethiopia President Obama convened...
20014    Jeb Bush Is Suddenly Attacking Trump. Here's W...
Name: text, Length: 20015, dtype: object


IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[[   30  2130     6 ...     0     0     0]
 [   98   753    21 ...     0     0     0]
 [   60   520    98 ...     0     0     0]
 ...
 [    1    69   256 ...     0     0     0]
 [24550 29989  6260 ...     0     0     0]
 [ 1897   331     8 ...     0     0     0]]
Loaded 400000 word vectors.
____________________
Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_10 (Embedding)     (None, 24177, 100)        16347600  
_________________________________________________________________
dropout_19 (Dropout)         (None, 24177, 100)        0         
_________________________________________________________________
conv1d_10 (Conv1D)           (None, 24174, 10)         4010      
_________________________________________________________________
max_pooling1d_10 (MaxPooling (None, 12087, 10)         0         
_________________________________________________________________
flat

KeyboardInterrupt: ignored

In [0]:
df[:5653]


id language  ... negation_count fpp_count
0     3.0  english  ...              0         3
1     4.0  english  ...              0         0
2     5.0  english  ...              0         2
3     6.0  english  ...              0         3
4     7.0  english  ...              0         0
...   ...      ...  ...            ...       ...
5648  NaN  english  ...              0         0
5649  NaN  english  ...              0         0
5650  NaN  english  ...              0         0
5651  NaN  english  ...              0         1
5652  NaN  english  ...              0         0

[5653 rows x 15 columns]